### ISSUE TITLE
Add upload font page.

### ISSUE THREAD

**Issue by alaabadran** [Mandooox/Arabic-Webfonts#3]
To add submit your font page in WP-Admin to allow font owners to submit their free and open fonts.
The fonts for now, should be submitted by email to info@fontface.me
Later, we will be working on a dynamic feature.
Please let me know if you have any suggestion or if you have any concerns.

**Comment by mohamdio** [comment]
we can create page on library site and announce about that, but to add this from dashboard this not allowed from WordPress team which can't add any personal info like email, sites..etc, so like i told you just create this page and i will announce about that in plugin page and on social also.
