### ISSUE TITLE
remove_month_filters

### ISSUE THREAD

**Issue by mahmoudkhalafallah** [Mandooox/Arabic-Webfonts#9]
Warning: Missing argument 2 for AWF_Post_Type::remove_month_filters() in D:\Creiden Work\Server\htdocs\t\wp-content\plugins\arabic-webfonts\includes\class-arabic-webfonts-post-type.php on line 169

Notice: Undefined variable: post_type in D:\Creiden Work\Server\htdocs\t\wp-content\plugins\arabic-webfonts\includes\class-arabic-webfonts-post-type.php on line 171

plugin version 1.4.4

**Comment by mohamdio** [comment]
Hello, mahmoud

Did this issue still exist ? and which WordPress version you are using ?
i tested plugin with all WordPress version up to latest version and this issue didn't appear with me

wait you reply
regards
